spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
          format_sql: true

loggin.level:
  org.hibernate.SQL: debug